# Generated by Django 4.0.1 on 2022-01-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_login_hash_expiration_delete_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_hash_expiration',
            field=models.DateTimeField(),
        ),
    ]
